# goreleaser.yml
# Build customization
build:
  main: main.go
  binary: utfbom-remove
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  ldflags: -s -w
release:
  github:
    owner: alastairruhm
    name: utfbom-remove
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - README.md
    - LICENSE

brew:
  github:
    owner: alastairruhm
    name: homebrew-tap

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: alastairruhm
    email: alastairruhm@gmail.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  caveats: ""

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/alastairruhm/utfbom-remove"

  # Your app's description.
  # Default is empty.
  description: "remove utf8 bom header of file"

  # Packages your package depends on.
  # dependencies:
  #   - git
  #   - zsh

  # Packages that conflict with your package.
  # conflicts:
  #   - svn
  #   - bash
  install: |
    bin.install "program"