# goreleaser.yml
# Build customization
build:
  main: main.go
  binary: utfbom-remove
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  ldflags: -s -w
release:
  github:
    owner: alstairruhm
    name: utfbom-remove
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - flora.default.conf
    - geoip.mmdb