language: go

osx_image: xcode8.3

go:
- 1.8
- 1.9

os:
- linux
- osx

before_install:
- go get github.com/golang/lint/golint
- go get github.com/FiloSottile/vendorcheck
# Install gometalinter and certain linters
- go get github.com/alecthomas/gometalinter
- go get github.com/gordonklaus/ineffassign
- go get golang.org/x/tools/cmd/goimports
- go get github.com/tsenart/deadcode
- go get github.com/Masterminds/glide

install:
- glide install -v

script:
- gometalinter --disable-all -E vet -E gofmt -E ineffassign -E goimports -E deadcode --tests --vendor ./...
- vendorcheck ./...
- go test -v -race -coverprofile=coverage.txt -covermode=atomic $(glide novendor)

after_success:
- bash <(curl -s https://codecov.io/bash)
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com
  slack:
    secure: CLC3S0Zpjh9J4Ro48BH5+bgBiB0qptvxRK9omN6yFsPTU3pHHpaLPMYf5bgY/hEcYWxF9f0cKpMRMTU9CMywUd2EP2OWwoZW+S9zEe/SCHvXaovG8KXw5TF9+aWyJV3H8cDjIUgLhoGTP0o3AGi7R/sQqhcVAplO8ZfhcpvGgs04ZjDW/ufvdcfmjL/frA7HmprUiiCPnOP2pFPRE43OAB1HXm+HlXiVHK8wfvg/tyRuxRkrtKFrIguUEhazqI8g+PtVSsabvvetygjGyo/KVg4vbsvp+tMoNqXp01DA7PqXmD5lIv1Djc1MswKutYFZGJf9yC2ZTuCs7D4/A6XSY/l1Tm4ewCxC747xMW8KQfaNxJpnm4X2mwCYV0L9iHGUbMZxd1TA0hwXNIpapQVv4NEc7ZAlvT49MBnh3adY3cyDLJ78UWdOuiG3Xdxdw8+8aHGVn2xg5gWNohMntDwUZWv22ilEWIUGu820MmvOEWkh3/aLEHr7ixziSYUjxmXsLoegCWUUHzFFbB5WsivNdjA08KSnPBfDlh3Tdfa0d78J8s98YOOa+m4W+15KTJim858rF8SW3/ga1pLQ0veAwszoVy8t8F07retGbZ1gZBis+FOFQbATHF/gtx1a6szgMFXiMgKJSBThK1DWK9rQXvXpjb/8PGBh5AGNn7bG3Tk=
