version: "{build}"

os: Windows Server 2016

platform: x64

image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\alastairruhm\utfbom-remove

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.8.x


install:
- set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
- go version
- go env
- go get github.com/Masterminds/glide
- glide install -v


build_script:
- for /f "" %%G in ('go list github.com/alastairruhm/utfbom-remove/... ^| find /i /v "/vendor/"') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)

# to disable automatic tests
test: off

# to disable deployment
deploy: off